apiVersion: v1
kind: Service
metadata:
  name: {{ include "nats.fullname" . }}-metrics
  labels:
    app: "{{ template "nats.name" . }}"
    chart: "{{ template "nats.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  type: {{ .Values.monitoring.service.type }}
  ports:
    - port: {{ .Values.metrics.port }}
      targetPort: {{ .Values.metrics.port }}
      protocol: TCP
      name: metrics
  selector:
    app: "{{ template "nats.name" . }}"
    release: {{ .Release.Name | quote }}

